name: CI

on:
  push:
    branches: [master, 'feature/*']
  pull_request:
    branches: [master]
  schedule:
    - cron: '0 2 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: yarn add @react-navigation/native react-native react @types/react @types/react-native
      - run: yarn test
